import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Syne } from 'next/font/google';

const syne = Syne({
  subsets: ['latin'],
  weight: ['400', '800'], // Kerakli vaznlar
  display: 'swap',        // Fallback shriftlar bilan uzluksiz yuklash
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
      className={`${syne.className} antialiased`}
      >
        <Provider>
          <Navbar/>
          {children}
          <Footer/>
        </Provider>
        
      </body>
    </html>
  );
}
