import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
          href="https://fonts.googleapis.com/css2?family=Syne:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`antialiased`}
      >
        <Provider>
          <Navbar/>
          {children}
          <Footer/>
        </Provider>
        
      </body>
    </html>
  );
}
